pool:
  vmImage: windows-2022

variables:
  #  GRADLE_USER_HOME: $(Pipeline.Workspace)/.gradle
  FLUTTER_CHANNEL: beta
  FLUTTER_VERSION: 3.1.0-9.0.pre

steps:
  - task: Cache@2
    inputs:
      key: 'gradleUserHome | "$(Agent.OS)" | **/build.gradle'
      restoreKeys: |
        gradleUserHome | "$(Agent.OS)"
        gradleUserHome
      path: $(GRADLE_USER_HOME)
    displayName: Gradle User Home Cache

  - task: Cache@2
    inputs:
      key: 'projectSpecificGradleCache | "$(Agent.OS)"'
      restoreKeys: projectSpecificGradleCache
      path: $(Build.SourcesDirectory)/android/.gradle
    displayName: Project Specific Gradle Cache

  - task: JavaToolInstaller@0
    inputs:
      versionSpec: '11'
      jdkArchitectureOption: 'x64'
      jdkSourceOption: 'PreInstalled'

  - task: Cache@2
    inputs:
      key: 'flutterSdk | "$(Agent.OS)"'
      restoreKeys: |
        flutterSdk | "$(Agent.OS)"
        flutterSdk
      path: '$(Agent.TempDirectory)'
    displayName: Flutter SDK Cache

  - task: FlutterInstall@0
    inputs:
      mode: 'auto'
      channel: '$(FLUTTER_CHANNEL)'
      version: 'custom'
      customVersion: '$(FLUTTER_VERSION)'

#  - task: Cache@2
#    inputs:
#      key: 'flutterPubCache | "$(Agent.OS)" | **/pubspec.yaml'
#      restoreKeys: |
#        flutterPubCache | "$(Agent.OS)"
#        flutterPubCache
#      path: '$(FlutterPubCachePath)'
#    displayName: Flutter Pub System Cache

  - task: FlutterBuild@0
    inputs:
      target: 'apk'
      projectDirectory: '.'
      debugMode: true
      splitPerAbi: true

  # - script: 'tree /f /a $(Build.SourcesDirectory)'
  #   displayName: 'Tree view of build folder'

  #  - script: 'ls -a $(Build.SourcesDirectory)/build/app/outputs/apk/debug/'
  #    displayName: 'List Contents of $(Build.SourcesDirectory)/build/app/outputs/apk/debug folder'

  #  - script: 'tree /f /a $(Agent.TempDirectory)'
  #    displayName: 'Tree view of $(Agent.TempDirectory) folder'

  - script: 'tree /f /a $(Pipeline.Workspace)'
    displayName: 'Tree view of $(Pipeline.Workspace) folder'

  - script : 'tree /f /a C:/hostedtoolcache/'
    displayName: 'Tree view of C:/hostedtoolcache folder'

  - publish: $(Build.SourcesDirectory)/build/app/outputs/apk/debug/app-armeabi-v7a-debug.apk
    artifact: Debug Apk for armeabi-v7a

  - publish: $(Build.SourcesDirectory)/build/app/outputs/apk/debug/app-arm64-v8a-debug.apk
    artifact: Debug Apk for arm64-v8a

  - publish: $(Build.SourcesDirectory)/build/app/outputs/apk/debug/app-x86_64-debug.apk
    artifact: Debug Apk for x86_64

  # - script: 'gradle --stop'
  #   displayName: Stop Gradle Daemon